.PHONY: clean All

All:
	@echo "----------Building project:[ FunctionsPrototype - Debug ]----------"
	@cd "FunctionsPrototype" && "$(MAKE)" -f  "FunctionsPrototype.mk"
clean:
	@echo "----------Cleaning project:[ FunctionsPrototype - Debug ]----------"
	@cd "FunctionsPrototype" && "$(MAKE)" -f  "FunctionsPrototype.mk" clean
