.PHONY: clean All

All:
	@echo "----------Building project:[ Derefencing - Debug ]----------"
	@cd "Derefencing" && "$(MAKE)" -f  "Derefencing.mk"
clean:
	@echo "----------Cleaning project:[ Derefencing - Debug ]----------"
	@cd "Derefencing" && "$(MAKE)" -f  "Derefencing.mk" clean
