.PHONY: clean All

All:
	@echo "----------Building project:[ LogicalOperator - Debug ]----------"
	@cd "LogicalOperator" && "$(MAKE)" -f  "LogicalOperator.mk"
clean:
	@echo "----------Cleaning project:[ LogicalOperator - Debug ]----------"
	@cd "LogicalOperator" && "$(MAKE)" -f  "LogicalOperator.mk" clean
