.PHONY: clean All

All:
	@echo "----------Building project:[ NestedLoop - Debug ]----------"
	@cd "NestedLoop" && "$(MAKE)" -f  "NestedLoop.mk"
clean:
	@echo "----------Cleaning project:[ NestedLoop - Debug ]----------"
	@cd "NestedLoop" && "$(MAKE)" -f  "NestedLoop.mk" clean
